# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 20:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_weather', '0004_place_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='weather',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
